apiVersion: kdop.kdop.io.vn/v1alpha1
kind: DockerJob
metadata:
  name: dockerjob-sample
spec:
  image: alpine:latest
  command: ["echo", "Hello from DockerJob!"]
  restartPolicy: Never
  dockerHostRef: dockerhost-sample