apiVersion: kdop.kdop.io.vn/v1alpha1
kind: DockerJob
metadata:
  name: ttl-job
spec:
  image: alpine:latest
  command: ["echo", "ttl-test"]
  restartPolicy: Never
  ttlSecondsAfterFinished: 15
  dockerHostRef: dockerhost-sample