## Append samples of your project ##
resources:
- kdop_v1alpha1_dockerhost.yaml
- kdop_v1alpha1_dockercontainer.yaml
- kdop_v1alpha1_dockerservice.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
